services:
    sitemap.console.generate:
        class: JeroenDesloovere\SitemapBundle\Console\GenerateSitemapCommand
        arguments:
            - "@sitemap.generator"
        tags:
            -  { name: console.command }
    sitemap.generator:
        class: JeroenDesloovere\SitemapBundle\Generator\SitemapGenerator
        public: true
        arguments:
            - "@router"
            - "%kernel.project_dir%/../"
            - "@sitemap.providers"
    sitemap.providers:
        class: JeroenDesloovere\SitemapBundle\Provider\SitemapProviders
